"use client";

import { useCallback, useEffect, useState } from "react";
import { ErrorState } from "@/components/error-state";
import { LoadingSkeleton } from "@/components/loading-skeleton";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { api } from "@/lib/api/client";
import type { AutonomyLevel, Preferences } from "@/lib/api/types";

const levels: Array<{ value: AutonomyLevel; label: string; description: string }> = [{ value: "observe", label: "Observe", description: "Record and explain recommendations without taking action." }, { value: "suggest", label: "Suggest", description: "Prepare actions for your explicit approval." }, { value: "safe_actions", label: "Safe Actions", description: "Run low-risk actions within your limits." }];
const categories = ["travel", "calendar", "messages", "subscriptions"];
const restrictions = ["Never move money or make purchases automatically.", "Never send external messages without an approved policy.", "Always require approval for high-risk actions."];
export function AutonomyManager() {
  const [preferences, setPreferences] = useState<Preferences | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState<unknown>(null), [saving, setSaving] = useState(false), [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(null); try { setPreferences(await api.getPreferences()); } catch (caught) { setError(caught); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const setLevel = (level: AutonomyLevel) => setPreferences((current) => current ? { ...current, autonomy_level: level } : current);
  const setCategory = (category: string, level: AutonomyLevel) => setPreferences((current) => current ? { ...current, category_behaviors: { ...current.category_behaviors, [category]: level } } : current);
  const setCap = (key: "daily_message_cap" | "daily_calendar_cap", value: string) => setPreferences((current) => current ? { ...current, [key]: Math.max(0, Number(value) || 0) } : current);
  const save = async () => { if (!preferences) return; setSaving(true); setError(null); setMessage(""); try { setPreferences(await api.updatePreferences({ autonomy_level: preferences.autonomy_level, category_behaviors: preferences.category_behaviors, daily_message_cap: preferences.daily_message_cap, daily_calendar_cap: preferences.daily_calendar_cap })); setMessage("Preferences saved."); } catch (caught) { setError(caught); } finally { setSaving(false); } };
  if (loading) return <main className="mx-auto max-w-4xl p-4 sm:p-6"><LoadingSkeleton className="h-80" label="Loading autonomy preferences" /></main>;
  if (!preferences) return <main className="mx-auto max-w-4xl space-y-3 p-4 sm:p-6"><ErrorState error={error ?? new Error("Preferences are unavailable.")} title="Autonomy preferences could not be loaded" /><Button onClick={() => void load()} type="button" variant="outline">Try again</Button></main>;
  const allCategories = [...new Set([...categories, ...Object.keys(preferences.category_behaviors)])];
  return <main className="mx-auto max-w-4xl space-y-6 p-4 pb-24 sm:p-6 md:pb-8"><header><h1 className="text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">Autonomy Centre</h1><p className="mt-2 text-sm leading-6 text-slate-600">Choose how FlowPilot responds, then set category limits. Guardrails below cannot be changed here.</p></header>{error ? <ErrorState error={error} title="Preferences could not be saved" /> : null}
    <Card><CardHeader><CardTitle>Default behaviour</CardTitle></CardHeader><CardContent><fieldset><legend className="sr-only">Default autonomy level</legend><div className="grid gap-3 md:grid-cols-3">{levels.map((level) => <label className="cursor-pointer rounded-lg border border-slate-200 p-4 has-[:checked]:border-indigo-500 has-[:checked]:bg-indigo-50" key={level.value}><input checked={preferences.autonomy_level === level.value} className="mr-2" name="autonomy" onChange={() => setLevel(level.value)} type="radio" value={level.value} /><span className="font-medium text-slate-900">{level.label}</span><span className="mt-2 block text-sm text-slate-600">{level.description}</span></label>)}</div></fieldset></CardContent></Card>
    <Card><CardHeader><CardTitle>Category behaviour and daily caps</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2">{allCategories.map((category) => <label className="text-sm font-medium text-slate-700" key={category}>{category.replaceAll("_", " ")}<select className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" onChange={(event) => setCategory(category, event.target.value as AutonomyLevel)} value={preferences.category_behaviors[category] ?? preferences.autonomy_level}>{levels.map((level) => <option key={level.value} value={level.value}>{level.label}</option>)}</select></label>)}</div><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Daily message cap<input className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" min="0" onChange={(event) => setCap("daily_message_cap", event.target.value)} type="number" value={preferences.daily_message_cap} /></label><label className="text-sm font-medium text-slate-700">Daily calendar cap<input className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" min="0" onChange={(event) => setCap("daily_calendar_cap", event.target.value)} type="number" value={preferences.daily_calendar_cap} /></label></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Fixed restrictions</CardTitle></CardHeader><CardContent><ul className="list-disc space-y-2 pl-5 text-sm text-slate-600">{(preferences.fixed_restrictions?.length ? preferences.fixed_restrictions : restrictions).map((restriction) => <li key={restriction}>{restriction}</li>)}</ul></CardContent></Card><div className="flex items-center gap-3"><Button disabled={saving} onClick={() => void save()} type="button">{saving ? "Saving…" : "Save preferences"}</Button><p aria-live="polite" className="text-sm text-emerald-700">{message}</p></div>
  </main>;
}
