"""Strict, versioned contract for standing-order compilation."""

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from app.connectors.base import ApprovalMode, ConnectorName
from app.models.enums import LifeEventType, RiskLevel
from app.services.action_registry import ACTION_REGISTRY

MAX_ACTION_TEMPLATES = 8
MAX_ENTITY_CONDITIONS = 12
ActionType = Literal[
    "travel.create_folder",
    "travel.save_ticket",
    "travel.upload_itinerary",
    "travel.upload_packing_checklist",
    "travel.create_calendar_event",
    "travel.get_weather",
    "travel.generate_documents",
    "travel.notify_family",
    "client.create_folder",
    "client.create_repository",
    "client.generate_documents",
    "client.create_calendar_event",
    "client.notify_client",
    "subscription.check_renewal",
    "salary.update_budget",
    "salary.propose_transfer",
]

# Compatibility projection; ACTION_REGISTRY is the source of policy truth.
ACTION_CATALOG: dict[str, tuple[str, RiskLevel, ApprovalMode]] = {
    definition.action_type: (
        definition.connector,
        definition.minimum_risk,
        definition.minimum_approval,
    )
    for definition in ACTION_REGISTRY
}

_RISK_ORDER = {RiskLevel.GREEN: 0, RiskLevel.YELLOW: 1, RiskLevel.RED: 2}
_APPROVAL_ORDER = {"automatic": 0, "approval_required": 1, "blocked": 2}


class EntityCondition(BaseModel):
    model_config = ConfigDict(extra="forbid")
    field: str = Field(min_length=1, max_length=80)
    operator: Literal["equals", "contains", "exists"]
    value: str | int | float | bool | None = None


class ActionTemplate(BaseModel):
    model_config = ConfigDict(extra="forbid")
    action_type: ActionType
    connector: ConnectorName
    input: dict[str, Any] = Field(default_factory=dict, max_length=32)
    risk_level: RiskLevel
    approval_mode: ApprovalMode

    @model_validator(mode="after")
    def validate_catalog_and_policy(self) -> "ActionTemplate":
        definition = ACTION_REGISTRY.get(self.action_type)
        if self.connector != definition.connector:
            raise ValueError(f"{self.action_type} requires the {definition.connector} connector")
        if _RISK_ORDER[self.risk_level] < _RISK_ORDER[definition.minimum_risk]:
            raise ValueError(f"{self.action_type} risk cannot be lowered")
        if self.risk_level is RiskLevel.RED and self.approval_mode == "automatic":
            raise ValueError("red-risk actions cannot be authorized automatically")
        if _APPROVAL_ORDER[self.approval_mode] < _APPROVAL_ORDER[definition.minimum_approval]:
            raise ValueError(f"{self.action_type} approval cannot be relaxed")
        return self


class CompiledRule(BaseModel):
    """A bounded rule generated by AI but validated entirely in application code."""

    model_config = ConfigDict(extra="forbid")
    schema_version: Literal["1.0"]
    trigger_event_types: list[LifeEventType] = Field(min_length=1, max_length=10)
    entity_conditions: list[EntityCondition] = Field(
        default_factory=list, max_length=MAX_ENTITY_CONDITIONS
    )
    action_templates: list[ActionTemplate] = Field(min_length=1, max_length=MAX_ACTION_TEMPLATES)
    explanation: str = Field(min_length=1, max_length=1_000)
    warnings: list[str] = Field(default_factory=list, max_length=20)

    @model_validator(mode="after")
    def reject_duplicate_actions(self) -> "CompiledRule":
        action_types = [action.action_type for action in self.action_templates]
        if len(action_types) != len(set(action_types)):
            raise ValueError("action templates must be unique")
        return self
