"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ActionDag } from "@/features/events/action-dag";
import { entityValue, formatDate, readable } from "@/features/events/event-utils";
import { ConfirmDialog } from "@/components/confirm-dialog";
import { EmptyState } from "@/components/empty-state";
import { ErrorState } from "@/components/error-state";
import { LoadingSkeleton } from "@/components/loading-skeleton";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { api } from "@/lib/api/client";
import type { EventDetail as EventRecord, Plan, PlanAction, TimelineEntry } from "@/lib/api/types";

type Intent = { kind: "execute" | "cancel" | "promote" | "retry" | "rollback"; action?: PlanAction };
const executeStatuses = ["draft", "policy_checked", "waiting_approval"], cancelStatuses = ["draft", "policy_checked", "running", "waiting_approval"];
export function EventDetail({ eventId }: { eventId: string }) {
  const [event, setEvent] = useState<EventRecord | null>(null), [plan, setPlan] = useState<Plan | null>(null), [timeline, setTimeline] = useState<TimelineEntry[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState<unknown>(null), [reveal, setReveal] = useState(false), [intent, setIntent] = useState<Intent | null>(null), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [nextEvent, nextTimeline] = await Promise.all([api.getEvent(eventId), api.getEventTimeline(eventId, { limit: 50 })]); setEvent(nextEvent); setTimeline(nextTimeline.items); setPlan(nextEvent.latest_plan ? await api.getPlan(nextEvent.latest_plan.id) : null); } catch (caught) { setError(caught); } finally { setLoading(false); } }, [eventId]);
  useEffect(() => { void load(); }, [load]);
  const applyAction = (updated: PlanAction) => setPlan((current) => current ? { ...current, actions: current.actions.map((action) => action.id === updated.id ? updated : action) } : current);
  const mutate = async () => { if (!intent || !plan) return; setBusy(true); setError(null); try { if (intent.kind === "execute") setPlan(await api.executePlan(plan.id)); else if (intent.kind === "cancel") setPlan(await api.cancelPlan(plan.id)); else if (intent.kind === "promote") setPlan(await api.promotePlan(plan.id)); else if (intent.action) applyAction(intent.kind === "retry" ? await api.retryAction(intent.action.id) : await api.rollbackAction(intent.action.id)); setIntent(null); } catch (caught) { setError(caught); } finally { setBusy(false); } };
  if (loading) return <main className="mx-auto max-w-6xl p-4 sm:p-6"><LoadingSkeleton className="h-96" label="Loading event details" /></main>;
  if (error && !event) return <main className="mx-auto max-w-6xl space-y-3 p-4 sm:p-6"><ErrorState error={error} title="Event could not be loaded" /><Button onClick={() => void load()} type="button" variant="outline">Try again</Button></main>;
  if (!event) return <main className="mx-auto max-w-6xl p-4 sm:p-6"><EmptyState description="The event may no longer be available." title="Event not found" /></main>;
  const dialogTitle = intent ? `${readable(intent.kind)} this ${intent.action ? "action" : "plan"}?` : "";
  return <main className="mx-auto max-w-6xl space-y-6 p-4 pb-24 sm:p-6 md:pb-8"><Link className="text-sm font-medium text-indigo-700 hover:underline" href="/dashboard/events">← All events</Link><header><h1 className="text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">{event.summary}</h1><p className="mt-2 text-sm text-slate-600">Interpreted from {readable(event.source)} on {formatDate(event.occurred_at)} · {readable(event.type)} · {Math.round(event.confidence * 100)}% confidence</p></header>{error ? <ErrorState error={error} title="The requested update failed" /> : null}
    <Card><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle>Entities</CardTitle><Button aria-pressed={reveal} onClick={() => setReveal((current) => !current)} size="sm" type="button" variant="outline">{reveal ? "Hide values" : "Show values"}</Button></div></CardHeader><CardContent><dl className="grid gap-3 text-sm sm:grid-cols-2">{event.entities.map((entity) => <div key={entity.kind}><dt className="font-medium text-slate-900">{readable(entity.kind)}{entity.is_sensitive ? " (sensitive)" : ""}</dt><dd className="mt-1 text-slate-600">{entityValue(entity, reveal)}</dd></div>) || <p className="text-slate-600">No entities were extracted.</p>}</dl></CardContent></Card>
    {plan ? <><Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>{plan.objective}</CardTitle><p className="mt-1 text-sm text-slate-600">{plan.planner_rationale ?? plan.summary ?? "No additional rationale provided."}</p></div><StatusBadge status={plan.status} /></div></CardHeader><CardContent className="flex flex-wrap gap-2"><p className="w-full text-sm text-slate-600">{plan.actions.length} actions · services: {[...new Set(plan.actions.map((action) => action.connector))].join(", ") || "none"} · {event.entities.filter((entity) => entity.is_sensitive).length} sensitive field{event.entities.filter((entity) => entity.is_sensitive).length === 1 ? "" : "s"} masked</p>{executeStatuses.includes(plan.status) ? <Button onClick={() => setIntent({ kind: "execute" })} type="button">Execute plan</Button> : null}{cancelStatuses.includes(plan.status) ? <Button onClick={() => setIntent({ kind: "cancel" })} type="button" variant="outline">Cancel plan</Button> : null}{plan.is_shadow ? <Button onClick={() => setIntent({ kind: "promote" })} type="button" variant="outline">Promote plan</Button> : null}</CardContent></Card>{plan.is_shadow ? <Card><CardHeader><CardTitle>Would have done</CardTitle></CardHeader><CardContent className="text-sm text-slate-600">{plan.summary ?? plan.objective}</CardContent></Card> : null}<ActionDag actions={plan.actions} /><section aria-label="Action recovery controls" className="flex flex-wrap gap-2">{plan.actions.filter((action) => action.status === "failed" || (action.status === "completed" && action.rollback_supported)).map((action) => <div className="flex items-center gap-2" key={action.id}><span className="text-sm text-slate-600">{readable(action.action_type)}</span>{action.status === "failed" ? <Button onClick={() => setIntent({ kind: "retry", action })} size="sm" type="button" variant="outline">Retry</Button> : null}{action.status === "completed" && action.rollback_supported ? <Button onClick={() => setIntent({ kind: "rollback", action })} size="sm" type="button" variant="outline">Roll back</Button> : null}</div>)}</section></> : <EmptyState description="A plan will appear here after the event is evaluated." title="No action plan yet" />}
    <section aria-labelledby="timeline-title"><h2 className="mb-3 text-lg font-semibold text-slate-950" id="timeline-title">Immutable timeline</h2>{timeline.length ? <ol className="space-y-3 border-l border-slate-200 pl-4">{timeline.map((entry) => <li key={entry.id}><p className="text-sm font-medium text-slate-900">{readable(entry.event_name)}</p><p className="text-sm text-slate-600">{formatDate(entry.created_at)} · {readable(entry.actor_type)}</p></li>)}</ol> : <p className="text-sm text-slate-600">No timeline entries have been recorded yet.</p>}</section>
    <ConfirmDialog busy={busy} confirmLabel={intent ? readable(intent.kind) : "Confirm"} description={intent?.kind === "rollback" ? "This reverses the completed action when the connector supports it." : "This changes the plan or action state and may trigger external work."} destructive={intent?.kind === "cancel" || intent?.kind === "rollback"} onCancel={() => setIntent(null)} onConfirm={() => void mutate()} open={intent !== null} title={dialogTitle} />
  </main>;
}
